apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-a
  namespace: tenant-a
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT:role/pod-irsa-a
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-b
  namespace: tenant-b
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT:role/pod-irsa-b
